[project]
name = "oath-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "playwright>=1.49.1",
    "requests>=2.32.3",
    "ruff>=0.9.2",
]
